module.exports = {
  'Eat Smart Asian Sesame Salad Kit': 1,
  'Lil\' Cados (6 Avocados)': 1,
  'Eat Smart Sweet Kale Salad Kit': 1,
  'Butternut Squash Agnolotti': 3,
  Carrot: 17,
  'Yellow Onion': 289,
  Garlic: 699,
  'Demi Baguette': 41,
  'Tomato Paste': 67,
  'Diced Tomatoes': 43,
  'Vegetable Stock Concentrate': 258,
  'Mushroom Stock Concentrate': 9,
  'Italian Seasoning': 91,
  'Cheese Tortelloni': 22,
  'Parmesan Cheese': 308,
  'Olive Oil': 1189,
  Butter: 727,
  Salt: 1454,
  Pepper: 1431,
  'Broccoli Florets': 78,
  Bacon: 24,
  Spaghetti: 32,
  'Cream Cheese': 56,
  'Garlic Herb Butter': 48,
  'Cheese Roux Concentrate': 1,
  Scallions: 418,
  'Roma Tomato': 263,
  Lime: 331,
  'Black Beans': 78,
  'Jasmine Rice': 178,
  'Chicken Breasts': 190,
  'Southwest Spice Blend': 141,
  'Mexican Cheese Blend': 31,
  'Chicken Stock Concentrate': 252,
  'Sour Cream': 544,
  'Vegetable Oil': 593,
  Jalapeño: 78,
  'Coleslaw Mix': 7,
  Cilantro: 199,
  'Tempura Mix': 6,
  Shrimp: 64,
  'Flour Tortillas': 99,
  Sugar: 276,
  Shallot: 279,
  'Yukon Gold Potatoes': 255,
  'Green Beans': 160,
  'Garlic Powder': 54,
  'Bavette Steak': 2,
  'Sherry Vinegar': 17,
  'Beef Stock Concentrate': 68,
  'Red Onion': 258,
  'Long Green Pepper': 29,
  'Ground Pork': 70,
  'Tex-Mex Paste': 3,
  'Pepper Jack Cheese': 23,
  Thyme: 109,
  Lemon: 410,
  'Fry Seasoning': 58,
  'Cream Sauce Base': 2,
  'Mozzarella Cheese': 90,
  'Ground Beef': 165,
  'Brioche Buns': 60,
  'Mixed Greens': 95,
  'Arborio Rice': 43,
  Sage: 20,
  'Butternut Squash': 22,
  Scallops: 5,
  Zucchini: 179,
  'Grape Tomatoes': 132,
  Chickpeas: 37,
  'Smoked Paprika': 45,
  'Israeli Couscous': 40,
  'Feta Cheese': 89,
  Penne: 8,
  Asparagus: 59,
  Chives: 60,
  'Panko Breadcrumbs': 225,
  'Sliced Almonds': 55,
  'Chili Flakes': 141,
  'Tuscan Heat Spice': 76,
  'Crushed Tomatoes': 80,
  'Chicken Cutlets': 43,
  Carrots: 150,
  Ginger: 131,
  'Sesame Seeds': 67,
  'Pork Chops': 58,
  'Teriyaki Sauce': 11,
  'Potato Bun': 20,
  Sriracha: 83,
  'Gouda Cheese': 11,
  Mayonnaise: 141,
  Honey: 143,
  'Soy Sauce': 133,
  'Korean Chili Flakes': 7,
  'Green Bell Pepper': 41,
  Pineapple: 41,
  'Chicken Breast Strips': 44,
  'Monterey Jack Cheese': 79,
  'Button Mushrooms': 71,
  Apple: 30,
  'Cheddar Cheese': 84,
  Rosemary: 67,
  'Chicken Demi-Glace': 25,
  Pecans: 16,
  'Dijon Mustard': 109,
  'Green Salsa': 6,
  'Poblano Pepper': 95,
  'Ground Cumin': 79,
  Turmeric: 18,
  'Chili Pepper': 57,
  'Bulgogi Sauce': 11,
  'Pork Cutlets': 11,
  'Bell Pepper': 70,
  'Italian Pork Sausage': 20,
  Parsley: 184,
  Tilapia: 22,
  'Truffle Zest': 11,
  'Spinach & Feta Egg Bite': 1,
  'Pork Tenderloin': 35,
  'Fig Jam': 16,
  'Balsamic Vinegar': 154,
  'Green Herb Blend': 2,
  'Ricotta Cheese': 19,
  Gnocchi: 9,
  'Marinara Sauce': 21,
  'Diced Steak': 4,
  'Sweet Potato': 121,
  'Sweet Soy Glaze': 2,
  'Creme Fraiche': 3,
  'Brown Sugar': 16,
  'Shredded Coconut': 7,
  'Dill Pickle': 15,
  Ketchup: 50,
  'Steelhead Trout': 3,
  Corn: 37,
  'Hot Sauce': 79,
  'Food Should Taste Good™ Blue Corn Tortilla Chips': 1,
  Farro: 25,
  'Chili Powder': 32,
  'Ocean Spray® Craisins® Dried Cranberries': 3,
  Arugula: 107,
  'Salsa Verde Sunflower Pepitas': 1,
  'Tunisian Spice Blend': 6,
  'Whole Wheat Pitas': 13,
  Couscous: 42,
  Yogurt: 27,
  'White Wine Vinegar': 142,
  'Yellow Mustard': 3,
  'Sesame Oil': 52,
  'Maple Syrup': 16,
  'Hudson River Fruit RubyFrost Apple': 2,
  'Gruyère Cheese': 13,
  'Chicken Legs': 19,
  Paprika: 19,
  'Apricot Jam': 20,
  Dill: 29,
  'Wasabi Paste': 10,
  Steak: 4,
  Rigatoni: 4,
  Rockfish: 3,
  'Blackening Spice': 18,
  Cornstarch: 31,
  'Sirloin Steak': 68,
  'Beef Demi-Glace': 33,
  'Duck Breast': 9,
  Orange: 25,
  'Red Wine Vinegar': 35,
  Guacamole: 12,
  'Harissa Powder': 9,
  'Bulgur Wheat': 13,
  'Persian Cucumber': 39,
  Kale: 42,
  Walnuts: 31,
  'Fresh Mozzarella': 71,
  'Ciabatta Bread': 32,
  Pesto: 49,
  Prosciutto: 16,
  Kiwi: 11,
  'Mexican Spice Blend': 18,
  'Cauliflower Florets': 21,
  'Basmati Rice': 64,
  'Smoky Cinnamon Paprika Spice': 5,
  'Dried Apricots': 9,
  Peanuts: 12,
  'Szechuan Paste': 1,
  'Brussels Sprouts': 33,
  'Fingerling Potatoes': 23,
  'Beef Tenderloin': 10,
  'Dried Thyme': 18,
  'Shredded Red Cabbage': 46,
  Eggs: 26,
  'Cavatappi Pasta': 21,
  Flour: 72,
  Milk: 70,
  'Sweet and Smoky BBQ Seasoning': 19,
  'Shredded Carrots': 24,
  'Cherry Jam': 11,
  Cucumber: 35,
  'Kidney Beans': 17,
  'Pulled Pork': 8,
  'Sweet Thai Chili Sauce': 2,
  'Lobster Ravioli': 10,
  Salmon: 25,
  'Za\'atar Spice Blend': 17,
  'BBQ Sauce': 24,
  'Basil Oil': 6,
  'Chipotle Powder': 46,
  Hummus: 4,
  'Shawarma Spice Blend': 2,
  'Steak Spice Blend': 7,
  'Potato Buns': 18,
  'Hot Smoked Paprika': 8,
  'Cremini Mushrooms': 6,
  'Hoisin Sauce': 33,
  'Herbes de Provence': 19,
  Tarragon: 23,
  'Black Peppercorns': 13,
  'Ranch Steak': 11,
  Pistachios: 7,
  Barramundi: 2,
  'Truffle Oil': 10,
  'Katsu Sauce': 1,
  Radishes: 30,
  'Celery Salt': 5,
  'Regal Springs Tilapia': 3,
  'Horseradish Powder': 7,
  'Mustard Seeds': 4,
  Pepitas: 26,
  Peas: 52,
  'Italian Chicken Sausage Mix': 30,
  'Mushroom Ravioli': 8,
  Avocado: 71,
  'Grilling Cheese': 15,
  'Ponzu Sauce': 1,
  'Italian Cheese Blend': 38,
  'Baby Carrots': 7,
  'Russet Potatoes': 18,
  'Penne Pasta': 30,
  'Maple Leaf Farms Duck Breast': 1,
  'Ancho Chili Powder': 5,
  'Dried Cherries': 8,
  'Turkish Spice Blend': 10,
  'Sabra Classic Hummus': 2,
  Flatbreads: 37,
  'Hudson River Fruit SnapDragon Apple': 2,
  'Australis Barramundi': 5,
  'Bacon & Swiss Egg Bites': 2,
  'Granny Smith Apple': 9,
  Brie: 3,
  'Cranberry Jam': 10,
  'Whole Grain Mustard': 8,
  Basil: 85,
  Sumac: 5,
  'Heirloom Grape Tomatoes': 62,
  'Colman\'s English Mustard': 1,
  Oregano: 28,
  'Diced Pork Tenderloin': 1,
  'Fajita Spice Blend': 11,
  'Wild Alaska Sockeye Salmon': 1,
  'Seafood Stock Concentrate': 5,
  'Oven-Ready Aluminum Trays': 1,
  'Three Little Pigs Pork Sausage': 2,
  'Spinach and Ricotta Ravioli': 6,
  'Enchilada Sauce': 2,
  'Orecchiette Pasta': 17,
  'Mini Bell Peppers': 3,
  'Curry Powder': 14,
  'Dried Chorizo': 10,
  'Colavita Crushed Tomatoes': 2,
  'Dried Oregano': 43,
  Quinoa: 28,
  'Sun-Dried Tomatoes': 16,
  'FirstFruits Opal Apple': 2,
  Celery: 24,
  'Sunflower Seeds': 7,
  Cashews: 13,
  Watercress: 7,
  'Golden Raisins': 11,
  'Romaine Lettuce': 23,
  'Beyond Burgers™': 2,
  'Annie\'s Organic Crescent Rolls': 1,
  'Ranch Spice': 7,
  'Yellow Squash': 25,
  'Fall Harvest Spice Blend': 5,
  'Dried Cranberries': 32,
  'Gemelli Pasta': 22,
  'Butternut Squash Pasta': 1,
  'White Bread': 13,
  'Microwavable White Rice': 6,
  'Tricolored Peppercorns': 12,
  'Crab Cakes': 8,
  'Sourdough Bread': 3,
  Spinach: 64,
  'Ground Turmeric': 3,
  'Place and Bake Brownies': 1,
  'Annie\'s Organic Flaky Biscuits': 1,
  'Pulled Chicken': 4,
  'Corn on the Cob': 47,
  'Garlic Oil': 2,
  'Hot Honey': 7,
  Plum: 3,
  Cornmeal: 1,
  'Black Truffle Butter': 2,
  'Tortilla Chips': 7,
  'Currant Jam': 3,
  'Thai Basil': 4,
  'Peanut Butter': 12,
  'Charcuterie Board': 1,
  'Annie\'s Cinnamon Rolls': 1,
  'Boneless Pork Chops': 14,
  '2% Reduced Fat Milk': 20,
  'Balsamic Glaze': 10,
  'Orzo Pasta': 27,
  'Black Pepper': 21,
  'Southwest Seasoning': 1,
  'Chicken Breast': 2,
  'Cherry Preserves': 2,
  'Flour Tortilla': 42,
  'Italian "So Delizioso" Seasoning': 1,
  'Caesar Dressing': 1,
  Parsnip: 14,
  'Pita Bread': 3,
  'Annie\'s Organic Cookie Dough': 1,
  'Wonton Wrappers': 10,
  Cinnamon: 8,
  'Green Olives': 7,
  'Black Olives': 8,
  Nutmeg: 10,
  'Meatloaf Spice Blend': 7,
  'Cara Cara Orange': 1,
  Ribeye: 18,
  'Whole Peeled Tomatoes': 8,
  'Mediterranean Spice Blend': 13,
  'Blood Orange': 5,
  Capers: 9,
  'Cannellini Beans': 14,
  'Chicken Thighs': 33,
  'Bartlett Pear': 3,
  'Taco Spice Blend': 2,
  'Enchilada Spice Blend': 6,
  'Fusilli Pasta': 12,
  'Ciabatta Roll': 3,
  'Moo Shu Spice Blend': 5,
  'Baby Red Potatoes': 12,
  'Macaroni Pasta': 3,
  'Fall Spice Blend': 6,
  'White Pepper': 5,
  'Ground Coriander': 3,
  'Coconut Crunch Cashews': 3,
  'Beefsteak Tomato': 10,
  'Baby Broccoli': 27,
  Linguine: 18,
  Pepperolio: 1,
  'Dried Rosemary': 9,
  'New York Strip Steak': 18,
  'Borlotti Beans': 3,
  'Corn Tortillas': 10,
  'Baby Bok Choy': 22,
  'Whole Wheat Israeli Couscous': 2,
  'Precooked Seven Whole Grains Rice': 1,
  'Multicolored Fingerling Potatoes': 2,
  'Pine Nuts': 15,
  'Ricotta Salata': 5,
  'Adobo Sauce': 6,
  'Snow Peas': 13,
  Edamame: 6,
  Dukkah: 4,
  'Lemon Juice': 4,
  'Minute Steak': 3,
  'Spinach and Artichoke Ravioli': 1,
  Tagliatelle: 8,
  'Orange Jam': 4,
  'Yakisoba Noodles': 5,
  Coriander: 17,
  Pancetta: 27,
  'Honey Sesame Pecans': 2,
  'Broccoli Slaw': 1,
  'Sweet Italian Pork Sausage': 28,
  'Chili Lime Butter': 2,
  'Cayenne Pepper': 17,
  Hazelnuts: 6,
  Freekeh: 3,
  Nectarine: 8,
  Mint: 50,
  Lemongrass: 7,
  'Thai Seasoning Blend': 7,
  'Naan Bread': 2,
  'Sugar Snap Peas': 22,
  Peach: 9,
  'Apple Cider Vinegar': 2,
  'BBQ Seasoning': 3,
  'Fish Sauce': 4,
  'Fresh Pork Chorizo': 13,
  Artichokes: 7,
  'Ground Turkey': 21,
  'Smoky Mexican Seasoning': 1,
  'Orange Grape Tomatoes': 2,
  'Goat Cheese': 7,
  Tahini: 3,
  'Jade Rice': 1,
  'Veggie Chorizo Crumbles': 4,
  Almonds: 3,
  'Tagliatelle Pasta': 1,
  'Mole Spice Blend': 2,
  'Cajun Spice Blend': 8,
  'Wooden Skewers': 20,
  'Portobello Mushrooms': 11,
  'Italian Veggie Crumbles': 1,
  'Chicken Tenders': 5,
  'White Onion': 1,
  'Skin-On Salmon Fillets': 2,
  'Collard Greens': 9,
  'Beef Stir-Fry': 11,
  Mango: 8,
  'Baby Portobello Mushrooms': 8,
  Tomato: 18,
  'Meyer Lemon': 3,
  'Kimchi Hot Sauce': 2,
  'Pho Concentrate': 5,
  'Organic Veggie Stock': 3,
  'Udon Noodles': 8,
  Grapefruit: 3,
  'Sparkling Wine* (not included)': 1,
  'Red Bell Pepper': 79,
  'Whole Wheat Spaghetti': 4,
  'Yellow Bell Pepper': 16,
  'Half Chicken': 8,
  'Whole Wheat Bread': 8,
  'Brown Rice': 20,
  'Shredded Brussels Sprouts': 1,
  'Baking Powder': 4,
  'White Potatoes': 4,
  Cauliflower: 8,
  'Skirt Steak': 4,
  'Asian Pear': 1,
  'Fuji Apple': 1,
  'Cuban Spice Blend': 1,
  'Applesauce Spice Blend': 1,
  'Chipotle Seitan Crumbles': 3,
  'Jerk Seasoning': 2,
  'Mixed Wild Mushrooms': 8,
  'Rice Noodles': 4,
  'Poultry Seasoning': 1,
  'Cinnamon Butter': 1,
  'Breakfast Sausage': 3,
  'Uncle Ben\'s® Ready Rice® Jasmine': 1,
  Pear: 5,
  Eggplant: 14,
  Tofu: 5,
  Leek: 5,
  'Wild Rice': 2,
  'Tuscan Kale': 10,
  'Boston Lettuce': 5,
  Catfish: 5,
  'Shakshuka Spice Blend': 2,
  'Cod Fillets': 8,
  'Wax Beans': 2,
  Tomatillos: 2,
  'Chipotles in Adobo': 7,
  'Pat LaFrieda Hamburger Blend': 1,
  'Maitake Mushrooms': 1,
  'Burrata and Lemon Zest Ravioli': 1,
  'SunGold Kiwi': 1,
  'Old Bay': 2,
  Polenta: 9,
  'Tri-Colored Quinoa': 1,
  'Chorizo Spice Blend': 3,
  'Lite Coconut Milk': 16,
  'Hoisin Sauce Jar': 10,
  'Mixed Olives': 14,
  'Frank\'s RedHot': 1,
  Grits: 5,
  Plantain: 1,
  'Farfalle Pasta': 2,
  'Aged Pomegranate Balsamic Vinegar': 1,
  Raviolini: 3,
  Lentils: 7,
  'Shelled Pistachios': 1,
  'Fish Seasoning Blend': 1,
  'Refried Beans': 1,
  Sole: 2,
  Potato: 2,
  'Marble Potatoes': 1,
  'Whole Wheat Penne Pasta': 1,
  'Swiss Chard': 3,
  Sunchokes: 4,
  'Beef Sirloin Tips': 6,
  'Whole Wheat Tortillas': 4,
  'Ras el Hanout': 4,
  'Red Quinoa': 2,
  'Dried Figs': 1,
  'Baby Potatoes': 4,
  'Short Rib Burger Blend': 1,
  'Green Leaf Lettuce': 2,
  'Baby Gem Lettuce': 5,
  'Cashew Pieces': 3,
  Berbere: 2,
  'Soy Sauce Jar': 12,
  'Pizza Dough': 16,
  'Sirloin Tips': 1,
  'Seitan Crumbles': 3,
  Tuna: 4,
  'Eggs*': 3,
  'Wheat Demi Baguette': 3,
  'Beef Tenderloin Tips': 4,
  'Chinese Eggplant': 1,
  'Garam masala': 4,
  'Yellow Plantain': 2,
  'Serrano Pepper': 5,
  'Chili Garlic Olives': 1,
  'PoBoy Rolls': 2,
  'Great Northern Beans': 1,
  'Pearl Barley': 4,
  'Butter Beans': 7,
  'Airline Chicken Breast': 1,
  Saffron: 3,
  'Flatiron Steak': 2,
  'Ground Lamb': 3,
  'Flour Spinach Tortillas': 1,
  Fusilloni: 3,
  'Mahi Mahi Filets': 3,
  'Bone-in Pork Chops': 2,
  'Red Grapes': 3,
  'Chuka Soba Noodles': 2,
  'Gluten Free Chicken Demi Glace': 2,
  'Pre-Cooked Beets': 5,
  'Swedish Spice Blend': 1,
  'Egg Noodles': 3,
  'Heavy Cream': 1,
  'Shell Pasta': 2,
  'Acorn Squash': 3,
  Fettuccine: 3,
  Turnip: 1,
  'Rainbow Trout': 1,
  'Shiitake Mushrooms': 3,
  'Delicata Squash': 1,
  Wheatberries: 2,
  'Red Lentils': 1,
  'Southwestern Chicken Sausage in Pork Casing': 1,
  '*Egg (optional)': 2,
  'Green Cabbage': 4,
  'Whole Wheat Pizza Dough': 2,
  'Cracked Freekeh': 2,
  'Fava Beans': 1,
  'Pumpernickel Bread': 1,
  Barley: 3,
  'Crumbled Goat Cheese': 7,
  'Ground Chicken': 3,
  'Plum tomatoes': 2,
  Pumpkin: 1,
  Bratwurst: 1,
  'Pretzel Bun': 1,
  'Basa Fillets': 2,
  'Cipollini Onions': 1,
  'Idaho Potato': 7,
  Trout: 1,
  'Fresh Figs': 2,
  'Spaghetti Squash': 2,
  'Steak Cutlets': 1,
  'Pearled Couscous': 2,
  'Black Eyed Peas': 1,
  Fenugreek: 1,
  Baguette: 7,
  'Chicken Sausage': 1,
  Cornflakes: 1,
  'Yellow Rice': 1,
  'Tandoori Spice': 1,
  'Chinese 5 Spice': 1,
  'Water Chestnuts': 1,
  'Dried Mint': 1,
  Cherries: 1,
  'Ground Juniper': 1,
  'Kale Sprouts': 1,
  'Corn Flour': 1,
  'Firm tofu': 1,
  'BBQ Spice Rub': 1,
  'Dried Dates': 1,
  'Pastrami Spice Blend': 1,
  Fennel: 5,
  'Lima Beans': 3,
  'Artichoke hearts': 5,
  'Cornbread Mix': 2,
  'Portugese rolls': 1,
  'Iceberg Lettuce': 3,
  'Creole Seasoning': 1,
  Rice: 3,
  Vermicelli: 2,
  'Seitan Strips': 1,
  'Special Spice Blend': 1,
  'Orange Juice': 1,
  'Purple Sweet Potato': 2,
  'Macadamia Nuts (nuts)': 1,
  'Black Thai Rice': 1,
  'Soba Noodles': 2,
  'English Cucumber': 3,
  Watermelon: 1,
  'Flank Steak': 1,
  'Rainbow carrots': 2,
  'Rice Flour': 1,
  'Seltzer Water': 1,
  Allspice: 3,
  'Mexican Oregano': 1,
  Seaweed: 1,
  'Porcini Mushroom Powder': 1,
  'Fregula Sarda': 2,
  Potatoes: 1,
  Tangelo: 1,
  Leeks: 1,
  Squid: 1,
  'Pearl Onions': 1,
  Nuteg: 1,
  'Buckwheat Soba Noodles': 1,
  'Silken Tofu': 1
}
